### ISSUE TITLE
Getting error `window is not defined`

### ISSUE THREAD

**Issue by paschalidi** [jscottsmith/react-scroll-parallax#6]
First things first, this is the most complete parallax library I have come across. Good job, many thanks.

Sometimes I am getting this error that has to do with `undefined window`, the message is as follows.

`500
Internal Server Error.
window is not defined
ReferenceError: window is not defined
    at /Users/christos.paschalidis/Documents/new-vimcar/node_modules/react-parallax-component/dist/index.min.js:19:2129
    at /Users/christos.paschalidis/Documents/new-vimcar/node_modules/react-parallax-component/dist/index.min.js:19:2061
    at e.exports (/Users/christos.paschalidis/Documents/new-vimcar/node_modules/react-parallax-component/dist/index.min.js:19:2347)
    at Object.<anonymous> (/Users/christos.paschalidis/Documents/new-vimcar/node_modules/react-parallax-component/dist/index.min.js:19:2826)
    at t (/Users/christos.paschalidis/Documents/new-vimcar/node_modules/react-parallax-component/dist/index.min.js:1:426)
    at Object.<anonymous> (/Users/christos.paschalidis/Documents/new-vimcar/node_modules/react-parallax-component/dist/index.min.js:17:2115)
    at Object.<anonymous> (/Users/christos.paschalidis/Documents/new-vimcar/node_modules/react-parallax-component/dist/index.min.js:17:2180)
    at t (/Users/christos.paschalidis/Documents/new-vimcar/node_modules/react-parallax-component/dist/index.min.js:1:426)
    at Object.<anonymous> (/Users/christos.paschalidis/Documents/new-vimcar/node_modules/react-parallax-component/dist/index.min.js:17:651)
    at Object.t.__esModule (/Users/christos.paschalidis/Documents/new-vimcar/node_modules/react-parallax-component/dist/index.min.js:17:2032)`

I am using `nextjs` as my framework not that I think this makes a big difference.

Thanks again.

**Comment by jscottsmith** [comment]
@paschalidi Not sure based on that error. Can you provide a repo for me to look at?

**Comment by jscottsmith** [comment]
Let me know if you are still encountering this issue.
